version: "3"

services:
  simpli_test_api:
    build:
      context: ./api/
    container_name: simpli_test_api
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE_HOST: ${POSTGRES_DATABASE_HOST}
      POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - 127.0.0.1:${API_PORT_EXPOSE}:${API_PORT}
    depends_on:
      simpli_test_db:
        condition: service_healthy

  simpli_test_db:
    image: postgres:13
    container_name: simpli_test_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data_db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DB_PORT_EXPOSE}:${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  simpli_test_webapp:
    build:
      context: ./webapp/
    container_name: simpli_test_webapp
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    
